# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(871, 591)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(550, 460, 161, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.sim_label = QtWidgets.QLabel(Dialog)
        self.sim_label.setGeometry(QtCore.QRect(70, 130, 111, 20))
        self.sim_label.setObjectName("sim_label")
        self.games_label = QtWidgets.QLabel(Dialog)
        self.games_label.setGeometry(QtCore.QRect(70, 160, 111, 20))
        self.games_label.setObjectName("games_label")
        self.games_label_2 = QtWidgets.QLabel(Dialog)
        self.games_label_2.setGeometry(QtCore.QRect(70, 260, 161, 20))
        self.games_label_2.setObjectName("games_label_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(70, 360, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 310, 101, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(230, 310, 101, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(230, 360, 101, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(380, 310, 101, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(380, 360, 101, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(530, 310, 101, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(530, 360, 101, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(Dialog)
        self.comboBox_9.setGeometry(QtCore.QRect(680, 310, 101, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(680, 360, 101, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.sim_length_line = QtWidgets.QLineEdit(Dialog)
        self.sim_length_line.setGeometry(QtCore.QRect(200, 130, 113, 20))
        self.sim_length_line.setObjectName("sim_length_line")
        self.turn_length_line = QtWidgets.QLineEdit(Dialog)
        self.turn_length_line.setGeometry(QtCore.QRect(200, 160, 113, 20))
        self.turn_length_line.setObjectName("turn_length_line")
        self.noise_line = QtWidgets.QLineEdit(Dialog)
        self.noise_line.setGeometry(QtCore.QRect(200, 190, 113, 20))
        self.noise_line.setObjectName("noise_line")
        self.sim_label_2 = QtWidgets.QLabel(Dialog)
        self.sim_label_2.setGeometry(QtCore.QRect(70, 190, 111, 20))
        self.sim_label_2.setObjectName("sim_label_2")
        self.reward_line = QtWidgets.QLineEdit(Dialog)
        self.reward_line.setGeometry(QtCore.QRect(620, 130, 41, 21))
        self.reward_line.setObjectName("reward_line")
        self.sim_label_3 = QtWidgets.QLabel(Dialog)
        self.sim_label_3.setGeometry(QtCore.QRect(550, 130, 51, 20))
        self.sim_label_3.setObjectName("sim_label_3")
        self.punishment_line = QtWidgets.QLineEdit(Dialog)
        self.punishment_line.setGeometry(QtCore.QRect(620, 190, 41, 21))
        self.punishment_line.setObjectName("punishment_line")
        self.sim_label_4 = QtWidgets.QLabel(Dialog)
        self.sim_label_4.setGeometry(QtCore.QRect(550, 190, 111, 20))
        self.sim_label_4.setObjectName("sim_label_4")
        self.temptation_line = QtWidgets.QLineEdit(Dialog)
        self.temptation_line.setGeometry(QtCore.QRect(760, 190, 41, 21))
        self.temptation_line.setObjectName("temptation_line")
        self.sim_label_5 = QtWidgets.QLabel(Dialog)
        self.sim_label_5.setGeometry(QtCore.QRect(690, 190, 111, 20))
        self.sim_label_5.setObjectName("sim_label_5")
        self.sucker_line = QtWidgets.QLineEdit(Dialog)
        self.sucker_line.setGeometry(QtCore.QRect(760, 130, 41, 21))
        self.sucker_line.setObjectName("sucker_line")
        self.player1_line = QtWidgets.QLineEdit(Dialog)
        self.player1_line.setGeometry(QtCore.QRect(170, 310, 41, 21))
        self.player1_line.setObjectName("player1_line")
        self.player2_line = QtWidgets.QLineEdit(Dialog)
        self.player2_line.setGeometry(QtCore.QRect(170, 360, 41, 21))
        self.player2_line.setObjectName("player2_line")      
        self.player3_line = QtWidgets.QLineEdit(Dialog)
        self.player3_line.setGeometry(QtCore.QRect(330, 310, 41, 21))
        self.player3_line.setObjectName("player3_line")   
        self.player4_line = QtWidgets.QLineEdit(Dialog)
        self.player4_line.setGeometry(QtCore.QRect(330, 360, 41, 21))
        self.player4_line.setObjectName("player4_line")
        self.player5_line = QtWidgets.QLineEdit(Dialog)
        self.player5_line.setGeometry(QtCore.QRect(480, 310, 41, 21))
        self.player5_line.setObjectName("player5_line")         
        self.player6_line = QtWidgets.QLineEdit(Dialog)
        self.player6_line.setGeometry(QtCore.QRect(480, 360, 41, 21))
        self.player6_line.setObjectName("player6_line")         
        self.player7_line = QtWidgets.QLineEdit(Dialog)
        self.player7_line.setGeometry(QtCore.QRect(630, 310, 41, 21))
        self.player7_line.setObjectName("player7_line")      
        self.player8_line = QtWidgets.QLineEdit(Dialog)
        self.player8_line.setGeometry(QtCore.QRect(630, 360, 41, 21))
        self.player8_line.setObjectName("player8_line")
        self.player9_line = QtWidgets.QLineEdit(Dialog)
        self.player9_line.setGeometry(QtCore.QRect(780, 310, 41, 21))
        self.player9_line.setObjectName("player9_line")              
        self.player10_line = QtWidgets.QLineEdit(Dialog)
        self.player10_line.setGeometry(QtCore.QRect(780, 360, 41, 21))
        self.player10_line.setObjectName("player10_line")              
        self.sim_label_6 = QtWidgets.QLabel(Dialog)
        self.sim_label_6.setGeometry(QtCore.QRect(690, 130, 51, 20))
        self.sim_label_6.setObjectName("sim_label_6")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(67, 230, 731, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(550, 80, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 381, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 80, 151, 31))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(70, 410, 731, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.games_label_3 = QtWidgets.QLabel(Dialog)
        self.games_label_3.setGeometry(QtCore.QRect(70, 440, 161, 20))
        self.games_label_3.setObjectName("games_label_3")
        self.csv_check = QtWidgets.QCheckBox(Dialog)
        self.csv_check.setGeometry(QtCore.QRect(70, 480, 70, 17))
        self.csv_check.setObjectName("csv_check")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(280, 430, 31, 141))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(320, 430, 61, 31))
        self.label_4.setObjectName("label_4")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(510, 430, 31, 141))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(550, 430, 141, 31))
        self.label_5.setObjectName("label_5")
        self.strategy_button = QtWidgets.QPushButton(Dialog)
        self.strategy_button.setGeometry(QtCore.QRect(320, 470, 111, 23))
        self.strategy_button.setObjectName("strategy_button")
        self.faq_button = QtWidgets.QPushButton(Dialog)
        self.faq_button.setGeometry(QtCore.QRect(320, 500, 111, 23))
        self.faq_button.setObjectName("faq_button")
        self.graphs_check = QtWidgets.QCheckBox(Dialog)
        self.graphs_check.setGeometry(QtCore.QRect(70, 510, 70, 17))
        self.graphs_check.setObjectName("graphs_check")
        self.pop_map_check = QtWidgets.QCheckBox(Dialog)
        self.pop_map_check.setGeometry(QtCore.QRect(70, 540, 101, 17))
        self.pop_map_check.setObjectName("pop_map_check")
        self.moran_check = QtWidgets.QCheckBox(Dialog)
        self.moran_check.setGeometry(QtCore.QRect(760, 460, 70, 17))
        self.moran_check.setObjectName("moran_check")   
        self.eco_check = QtWidgets.QCheckBox(Dialog)
        self.eco_check.setGeometry(QtCore.QRect(760, 490, 70, 17))
        self.eco_check.setObjectName("eco_check")
        self.tour_check = QtWidgets.QCheckBox(Dialog)
        self.tour_check.setGeometry(QtCore.QRect(760, 520, 101, 17))
        self.tour_check.setObjectName("tour_check")                
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(420, 80, 31, 141))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sim_label.setText(_translate("Dialog", "Simulation Length"))
        self.sim_length_line.setText(_translate("Dialog", "10"))
        self.games_label.setText(_translate("Dialog", "Games per Generation"))
        self.turn_length_line.setText(_translate("Dialog", "10"))
        self.noise_line.setText(_translate("Dialog", "0"))
        self.games_label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Participant Types</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Dialog", "Defector"))        
        self.comboBox_2.setItemText(0, _translate("Dialog", "Cooperator"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Tit For Tat"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Tit for Two Tats"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "Grudger"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "Revised Downing"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "Nydegger"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "Copier"))
        self.comboBox_9.setItemText(0, _translate("Dialog", "Pavlov"))
        self.comboBox_10.setItemText(0, _translate("Dialog", "Random"))
        
        self.player1_line.setText(_translate("Dialog", "1"))      
        self.player2_line.setText(_translate("Dialog", "1"))                    
        self.player3_line.setText(_translate("Dialog", "0"))                
        self.player4_line.setText(_translate("Dialog", "0"))                      
        self.player5_line.setText(_translate("Dialog", "0"))                      
        self.player6_line.setText(_translate("Dialog", "0"))                      
        self.player7_line.setText(_translate("Dialog", "0"))                     
        self.player8_line.setText(_translate("Dialog", "0"))                     
        self.player9_line.setText(_translate("Dialog", "0"))                     
        self.player10_line.setText(_translate("Dialog", "0"))                      
        self.sim_label_2.setText(_translate("Dialog", "Error Probability Ratio"))
        self.sim_label_3.setText(_translate("Dialog", "Reward"))
        self.reward_line.setText(_translate("Dialog", "3"))
        self.sim_label_4.setText(_translate("Dialog", "Punishment"))
        self.punishment_line.setText(_translate("Dialog", "1"))        
        self.sim_label_5.setText(_translate("Dialog", "Temptation"))
        self.temptation_line.setText(_translate("Dialog", "5"))
        self.sim_label_6.setText(_translate("Dialog", "Sucker"))
        self.sucker_line.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Payoffs</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#000000;\">PRISONER\'S DILEMMA SIM</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Main Parameters</span></p></body></html>"))
        self.games_label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Output Settings</span></p></body></html>"))
        self.csv_check.setText(_translate("Dialog", "CSV File"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Help</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Run Simulation</span></p></body></html>"))
        self.strategy_button.setText(_translate("Dialog", "Strategy Reference"))
        self.faq_button.setText(_translate("Dialog", "FAQ"))
        self.graphs_check.setText(_translate("Dialog", "Graphs"))
        self.pop_map_check.setText(_translate("Dialog", "Population Map"))
        self.moran_check.setText(_translate("Dialog", "Moran"))
        self.eco_check.setText(_translate("Dialog", "Ecological"))
        self.tour_check.setText(_translate("Dialog", "Tournament"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

